services:

  db:
    container_name: postgres_container
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=zipit
      - POSTGRES_PASSWORD=math
      - POSTGRES_USER=postgres
    volumes:
      - C:/Users/Matheesh/docker/volumes:/var/lib/postgresql/data

    restart: always
  backend:
    build:    # We can also use build: .
      dockerfile: Dockerfile
    container_name: zipit_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://postgres_container:5432/zipit
      db-username: postgres
      db-password: math
    depends_on:
      - db